import { createClient } from "@supabase/supabase-js";
import { jsPDF } from "jspdf";
import crypto from "crypto";

export async function generateDigitalAgreement(profile: {
  fullName: string;
  masked_id: string;
  permanent_address: string;
  dob?: string;
}, property: {
  id: string;
  title: string;
  address: string;
  monthly_rent: number;
}, meta?: {
  bookingId?: string;
  studentId?: string;
  ownerId?: string;
}) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  let y = 50;
  doc.setFontSize(20);
  doc.text("NoidaStay Digital Rent Agreement", 40, y);
  y += 28;
  doc.setFontSize(12);
  doc.text(`Tenant: ${profile.fullName}`, 40, y);
  y += 18;
  doc.text(`Aadhaar (masked): ${profile.masked_id}`, 40, y);
  y += 18;
  doc.text(`Property: ${property.title}`, 40, y);
  y += 18;
  doc.text(`Address: ${property.address}`, 40, y);
  y += 18;
  doc.text(`Monthly Rent: ₹${property.monthly_rent.toLocaleString("en-IN")}`, 40, y);
  y += 28;

  doc.setFontSize(13);
  doc.text("1. Notice Period", 40, y);
  y += 18;
  doc.setFontSize(10);
  doc.text("Tenant or owner may terminate with 30 days written notice. Rent and deposit terms apply.", 40, y, { maxWidth: 520 });
  y += 28;
  doc.setFontSize(13);
  doc.text("2. Refundable Security Deposit", 40, y);
  y += 18;
  doc.setFontSize(10);
  doc.text("Deposit is refundable after property inspection and dues clearance at end of tenure.", 40, y, { maxWidth: 520 });
  y += 28;
  doc.setFontSize(13);
  doc.text("3. NoidaStay Brokerage Terms", 40, y);
  y += 18;
  doc.setFontSize(10);
  doc.text("NoidaStay provides digital broker services for legal agreement generation, e-stamping assistance, and deposit protection.", 40, y, { maxWidth: 520 });
  y += 28;
  doc.text("This agreement is generated by NoidaStay Digital Broker and is legally binding upon acceptance.", 40, y, { maxWidth: 520 });

  const pdfArray = doc.output("arraybuffer");
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!supabaseUrl || !supabaseKey) {
    throw new Error("Supabase config missing");
  }

  const supabase = createClient(supabaseUrl, supabaseKey);
  const bucketName = "vault-documents";
  const existingBuckets = await supabase.storage.listBuckets();
  const bucketExists = existingBuckets.data?.some((b: any) => b.name === bucketName);
  if (!bucketExists) {
    await supabase.storage.createBucket(bucketName, { public: false });
  }

  const filePath = `${property.id}-${Date.now()}.pdf`;
  const { error } = await supabase.storage.from(bucketName).upload(filePath, Buffer.from(pdfArray), {
    contentType: "application/pdf",
    upsert: true,
  });
  if (error) {
    throw error;
  }

  const documentHash = crypto.createHash("sha256").update(Buffer.from(pdfArray)).digest("hex");
  await supabase.from("legal_agreements").insert({
    booking_id: meta?.bookingId || null,
    student_id: meta?.studentId || null,
    owner_id: meta?.ownerId || null,
    file_path: filePath,
    document_hash: documentHash,
    signed_at: new Date().toISOString(),
    security_deposit_escrowed: false,
  });

  const { data: urlData, error: signError } = await supabase.storage.from(bucketName).createSignedUrl(filePath, 60 * 60);
  if (signError) {
    throw signError;
  }
  return urlData.signedUrl;
}
